# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c697a2289048456953f75f2ac5a13e6fd97208a7908b72d67ee608c6ca1c5479fcec80ce2852a80dcb1f8739ff9b0ac219bf4ffdebb3f809dac96ea9bc006e

test:
  secret_key_base: 3b13ca734998e590172595d3a856191dd0631f7ce30c22328f15a7a83f33a13ba3305ef625a1c9d2166f23cc85309c9c24954f1601a40db765279883847e2c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
